version: "3.9"
services:
  keycloak:
    container_name: keycloak-booking
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - local
    command:
      - "start-dev"

networks:
  local:
    name: local
    driver: bridge
volumes:
  keycloak:
    driver: local